CREATE TABLE IF NOT EXISTS users
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	nickName VARCHAR(30) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	firstName VARCHAR(255),
	lastName VARCHAR(255),
	uid CHAR(16),
	PRIMARY KEY (id),
	UNIQUE KEY (nickName),
	UNIQUE KEY (email)
) ENGINE=InnoDb;
